### ISSUE TITLE
Exception handling in do_set 

### ISSUE THREAD

**Issue by colinsurprenant** [logstash-plugins/logstash-filter-memcached#23]
logstash crashes when memcached servers becomes unavailable. 

```
W, [2019-11-14T08:15:41.117628 #1]  WARN -- : memcached-03:11211 failed (count: 0) EOFError: End of file reached
W, [2019-11-14T08:15:41.320959 #1]  WARN -- : memcached-03:11211 failed (count: 0) Errno::EPIPE: Broken pipe - No message available
W, [2019-11-14T08:15:41.352324 #1]  WARN -- : memcached-03:11211 failed (count: 1) Errno::ECONNREFUSED: Connection refused - connect(2) for "memcached-03" port 11211
W, [2019-11-14T08:15:41.352323 #1]  WARN -- : memcached-03:11211 failed (count: 1) Errno::ECONNREFUSED: Connection refused - connect(2) for "memcached-03" port 11211
W, [2019-11-14T08:15:41.358390 #1]  WARN -- : memcached-03:11211 is down
W, [2019-11-14T08:15:41.359376 #1]  WARN -- : memcached-03:11211 is down
W, [2019-11-14T08:16:05.118757 #1]  WARN -- : memcached-02:11211 failed (count: 0) EOFError: End of file reached
W, [2019-11-14T08:16:05.151353 #1]  WARN -- : memcached-02:11211 failed (count: 0) Errno::EPIPE: Broken pipe - No message available
W, [2019-11-14T08:16:05.152609 #1]  WARN -- : memcached-02:11211 failed (count: 1) Errno::ECONNREFUSED: Connection refused - connect(2) for "memcached-02" port 11211
W, [2019-11-14T08:16:05.153428 #1]  WARN -- : memcached-02:11211 is down
W, [2019-11-14T08:16:05.165181 #1]  WARN -- : memcached-02:11211 failed (count: 1) Errno::ECONNREFUSED: Connection refused - connect(2) for "memcached-02" port 11211
W, [2019-11-14T08:16:05.165753 #1]  WARN -- : memcached-02:11211 is down
[2019-11-14T08:16:09,033][ERROR][org.logstash.execution.WorkerLoop] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.
org.jruby.exceptions.RuntimeError: (RingError) No server available
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.dalli_minus_2_dot_7_dot_10.lib.dalli.ring.server_for_key(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/dalli-2.7.10/lib/dalli/ring.rb:46) ~[?:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.dalli_minus_2_dot_7_dot_10.lib.dalli.client.perform(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/dalli-2.7.10/lib/dalli/client.rb:367) ~[?:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.dalli_minus_2_dot_7_dot_10.lib.dalli.client.set(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/dalli-2.7.10/lib/dalli/client.rb:130) ~[?:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_memcached_minus_1_dot_0_dot_1.lib.logstash.filters.memcached.do_set(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-memcached-1.0.1/lib/logstash/filters/memcached.rb:137) ~[?:?]
	at org.jruby.RubyHash.each(org/jruby/RubyHash.java:1419) ~[jruby-complete-9.2.7.0.jar:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_memcached_minus_1_dot_0_dot_1.lib.logstash.filters.memcached.do_set(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-memcached-1.0.1/lib/logstash/filters/memcached.rb:135) ~[?:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.dalli_minus_2_dot_7_dot_10.lib.dalli.client.multi(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/dalli-2.7.10/lib/dalli/client.rb:50) ~[?:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_memcached_minus_1_dot_0_dot_1.lib.logstash.filters.memcached.do_set(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-memcached-1.0.1/lib/logstash/filters/memcached.rb:134) ~[?:?]
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_memcached_minus_1_dot_0_dot_1.lib.logstash.filters.memcached.filter(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-memcached-1.0.1/lib/logstash/filters/memcached.rb:84) ~[?:?]
	at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.do_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:143) ~[?:?]
	at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.multi_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:162) ~[?:?]
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1792) ~[jruby-complete-9.2.7.0.jar:?]
	at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.multi_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159) ~[?:?]
	at org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multi_filter(org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:115) ~[logstash-core.jar:?]
	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:239) ~[?:?]
warning: thread "[p049_arcsight-asa-01-flow]>worker11" terminated with exception (report_on_exception is true):
java.lang.IllegalStateException: org.jruby.exceptions.RuntimeError: (RingError) No server available
	at org.logstash.execution.WorkerLoop.run(org/logstash/execution/WorkerLoop.java:85)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(jdk/internal/reflect/GeneratedMethodAccessor82)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:440)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:304)
	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:239)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:295)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:274)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:270)
	at java.lang.Thread.run(java/lang/Thread.java:834)
Caused by: org.jruby.exceptions.RuntimeError: (RingError) No server available
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.dalli_minus_2_dot_7_dot_10.lib.dalli.ring.server_for_key(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/dalli-2.7.10/lib/dalli/ring.rb:46)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.dalli_minus_2_dot_7_dot_10.lib.dalli.client.perform(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/dalli-2.7.10/lib/dalli/client.rb:367)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.dalli_minus_2_dot_7_dot_10.lib.dalli.client.set(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/dalli-2.7.10/lib/dalli/client.rb:130)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_memcached_minus_1_dot_0_dot_1.lib.logstash.filters.memcached.do_set(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-memcached-1.0.1/lib/logstash/filters/memcached.rb:137)
	at org.jruby.RubyHash.each(org/jruby/RubyHash.java:1419)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_memcached_minus_1_dot_0_dot_1.lib.logstash.filters.memcached.do_set(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-memcached-1.0.1/lib/logstash/filters/memcached.rb:135)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.dalli_minus_2_dot_7_dot_10.lib.dalli.client.multi(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/dalli-2.7.10/lib/dalli/client.rb:50)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_memcached_minus_1_dot_0_dot_1.lib.logstash.filters.memcached.do_set(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-memcached-1.0.1/lib/logstash/filters/memcached.rb:134)
	at usr.share.logstash.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_filter_minus_memcached_minus_1_dot_0_dot_1.lib.logstash.filters.memcached.filter(/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-memcached-1.0.1/lib/logstash/filters/memcached.rb:84)
	at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.do_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:143)
	at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.multi_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:162)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1792)
	at usr.share.logstash.logstash_minus_core.lib.logstash.filters.base.multi_filter(/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159)
	at org.logstash.config.ir.compiler.AbstractFilterDelegatorExt.multi_filter(org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:115)
	at usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:239)
[2019-11-14T08:16:09,153][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>java.lang.IllegalStateException: org.jruby.exceptions.RuntimeError: (RingError) No server available, :backtrace=>["org.logstash.execution.WorkerLoop.run(org/logstash/execution/WorkerLoop.java:85)", "jdk.internal.reflect.GeneratedMethodAccessor82.invoke(jdk/internal/reflect/GeneratedMethodAccessor82)", "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:566)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:440)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:304)", "usr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:239)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:295)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:274)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:270)", "java.lang.Thread.run(java/lang/Thread.java:834)"]}
[2019-11-14T08:16:09,317][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
[2019-11-14T08:16:09,477][ERROR][logstash.inputs.udp      ] UDP listener died {:exception=>#<IOError: closed stream>, :backtrace=>["org/jruby/RubyIO.java:3552:in `select'", ":1:in `'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-udp-3.3.4/lib/logstash/inputs/udp.rb:68:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:309:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:302:in `block in start_input'"]}
```

It appears the dalli client eventually throws a `RuntimeError: (RingError) No server available` when no server is available. This appens at https://github.com/logstash-plugins/logstash-filter-memcached/blob/db53ae6d03a16338ca0a54cae406da7b16fe2b14/lib/logstash/filters/memcached.rb#L137 and there is no exception handling to handle such a condition which leads to crashing the plugin and logstash. 

it looks like we could improve this by catching this exception and probably go into a reconnection strategy?

**Comment by colinsurprenant** [comment]
submitted fix in #25
